# Generated by Django 5.1.4 on 2025-01-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_slug_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='abcd', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
